// Mapping of SQLGetInfo info types to their result representation.
//
// GENERATED from the aInfoTypes table in src/connection.cpp against the values in
// rust/constants.rs.  Becomes the source of truth when the C++ sources are removed.

#[derive(Clone, Copy, PartialEq)]
pub enum InfoKind {
    YesNo,
    Str,
    UInt,
    USmallInt,
}

pub const GETINFO_TYPES: &[(u16, InfoKind)] = &[
    (48, InfoKind::UInt),         // SQL_CONVERT_FUNCTIONS
    (53, InfoKind::UInt),         // SQL_CONVERT_BIGINT
    (54, InfoKind::UInt),         // SQL_CONVERT_BINARY
    (55, InfoKind::UInt),         // SQL_CONVERT_BIT
    (56, InfoKind::UInt),         // SQL_CONVERT_CHAR
    (57, InfoKind::UInt),         // SQL_CONVERT_DATE
    (58, InfoKind::UInt),         // SQL_CONVERT_DECIMAL
    (59, InfoKind::UInt),         // SQL_CONVERT_DOUBLE
    (60, InfoKind::UInt),         // SQL_CONVERT_FLOAT
    (61, InfoKind::UInt),         // SQL_CONVERT_INTEGER
    (62, InfoKind::UInt),         // SQL_CONVERT_LONGVARCHAR
    (63, InfoKind::UInt),         // SQL_CONVERT_NUMERIC
    (64, InfoKind::UInt),         // SQL_CONVERT_REAL
    (65, InfoKind::UInt),         // SQL_CONVERT_SMALLINT
    (66, InfoKind::UInt),         // SQL_CONVERT_TIME
    (67, InfoKind::UInt),         // SQL_CONVERT_TIMESTAMP
    (68, InfoKind::UInt),         // SQL_CONVERT_TINYINT
    (69, InfoKind::UInt),         // SQL_CONVERT_VARBINARY
    (70, InfoKind::UInt),         // SQL_CONVERT_VARCHAR
    (71, InfoKind::UInt),         // SQL_CONVERT_LONGVARBINARY
    (122, InfoKind::UInt),        // SQL_CONVERT_WCHAR
    (123, InfoKind::UInt),        // SQL_CONVERT_INTERVAL_DAY_TIME
    (124, InfoKind::UInt),        // SQL_CONVERT_INTERVAL_YEAR_MONTH
    (125, InfoKind::UInt),        // SQL_CONVERT_WLONGVARCHAR
    (126, InfoKind::UInt),        // SQL_CONVERT_WVARCHAR
    (173, InfoKind::UInt),        // SQL_CONVERT_GUID
    (20, InfoKind::YesNo),        // SQL_ACCESSIBLE_PROCEDURES
    (19, InfoKind::YesNo),        // SQL_ACCESSIBLE_TABLES
    (116, InfoKind::USmallInt),   // SQL_ACTIVE_ENVIRONMENTS
    (169, InfoKind::UInt),        // SQL_AGGREGATE_FUNCTIONS
    (117, InfoKind::UInt),        // SQL_ALTER_DOMAIN
    (86, InfoKind::UInt),         // SQL_ALTER_TABLE
    (10021, InfoKind::UInt),      // SQL_ASYNC_MODE
    (120, InfoKind::UInt),        // SQL_BATCH_ROW_COUNT
    (121, InfoKind::UInt),        // SQL_BATCH_SUPPORT
    (82, InfoKind::UInt),         // SQL_BOOKMARK_PERSISTENCE
    (114, InfoKind::USmallInt),   // SQL_CATALOG_LOCATION
    (10003, InfoKind::YesNo),     // SQL_CATALOG_NAME
    (41, InfoKind::Str),          // SQL_CATALOG_NAME_SEPARATOR
    (42, InfoKind::Str),          // SQL_CATALOG_TERM
    (92, InfoKind::UInt),         // SQL_CATALOG_USAGE
    (10004, InfoKind::Str),       // SQL_COLLATION_SEQ
    (87, InfoKind::YesNo),        // SQL_COLUMN_ALIAS
    (22, InfoKind::USmallInt),    // SQL_CONCAT_NULL_BEHAVIOR
    (74, InfoKind::USmallInt),    // SQL_CORRELATION_NAME
    (127, InfoKind::UInt),        // SQL_CREATE_ASSERTION
    (128, InfoKind::UInt),        // SQL_CREATE_CHARACTER_SET
    (129, InfoKind::UInt),        // SQL_CREATE_COLLATION
    (130, InfoKind::UInt),        // SQL_CREATE_DOMAIN
    (131, InfoKind::UInt),        // SQL_CREATE_SCHEMA
    (132, InfoKind::UInt),        // SQL_CREATE_TABLE
    (133, InfoKind::UInt),        // SQL_CREATE_TRANSLATION
    (134, InfoKind::UInt),        // SQL_CREATE_VIEW
    (23, InfoKind::USmallInt),    // SQL_CURSOR_COMMIT_BEHAVIOR
    (24, InfoKind::USmallInt),    // SQL_CURSOR_ROLLBACK_BEHAVIOR
    (16, InfoKind::Str),          // SQL_DATABASE_NAME
    (2, InfoKind::Str),           // SQL_DATA_SOURCE_NAME
    (25, InfoKind::YesNo),        // SQL_DATA_SOURCE_READ_ONLY
    (119, InfoKind::UInt),        // SQL_DATETIME_LITERALS
    (17, InfoKind::Str),          // SQL_DBMS_NAME
    (18, InfoKind::Str),          // SQL_DBMS_VER
    (170, InfoKind::UInt),        // SQL_DDL_INDEX
    (26, InfoKind::UInt),         // SQL_DEFAULT_TXN_ISOLATION
    (10002, InfoKind::YesNo),     // SQL_DESCRIBE_PARAMETER
    (171, InfoKind::Str),         // SQL_DM_VER
    (6, InfoKind::Str),           // SQL_DRIVER_NAME
    (77, InfoKind::Str),          // SQL_DRIVER_ODBC_VER
    (7, InfoKind::Str),           // SQL_DRIVER_VER
    (136, InfoKind::UInt),        // SQL_DROP_ASSERTION
    (137, InfoKind::UInt),        // SQL_DROP_CHARACTER_SET
    (138, InfoKind::UInt),        // SQL_DROP_COLLATION
    (139, InfoKind::UInt),        // SQL_DROP_DOMAIN
    (140, InfoKind::UInt),        // SQL_DROP_SCHEMA
    (141, InfoKind::UInt),        // SQL_DROP_TABLE
    (142, InfoKind::UInt),        // SQL_DROP_TRANSLATION
    (143, InfoKind::UInt),        // SQL_DROP_VIEW
    (144, InfoKind::UInt),        // SQL_DYNAMIC_CURSOR_ATTRIBUTES1
    (145, InfoKind::UInt),        // SQL_DYNAMIC_CURSOR_ATTRIBUTES2
    (27, InfoKind::YesNo),        // SQL_EXPRESSIONS_IN_ORDERBY
    (84, InfoKind::USmallInt),    // SQL_FILE_USAGE
    (146, InfoKind::UInt),        // SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1
    (147, InfoKind::UInt),        // SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2
    (81, InfoKind::UInt),         // SQL_GETDATA_EXTENSIONS
    (88, InfoKind::USmallInt),    // SQL_GROUP_BY
    (28, InfoKind::USmallInt),    // SQL_IDENTIFIER_CASE
    (29, InfoKind::Str),          // SQL_IDENTIFIER_QUOTE_CHAR
    (148, InfoKind::UInt),        // SQL_INDEX_KEYWORDS
    (149, InfoKind::UInt),        // SQL_INFO_SCHEMA_VIEWS
    (172, InfoKind::UInt),        // SQL_INSERT_STATEMENT
    (73, InfoKind::YesNo),        // SQL_INTEGRITY
    (150, InfoKind::UInt),        // SQL_KEYSET_CURSOR_ATTRIBUTES1
    (151, InfoKind::UInt),        // SQL_KEYSET_CURSOR_ATTRIBUTES2
    (89, InfoKind::Str),          // SQL_KEYWORDS
    (113, InfoKind::YesNo),       // SQL_LIKE_ESCAPE_CLAUSE
    (10022, InfoKind::UInt),      // SQL_MAX_ASYNC_CONCURRENT_STATEMENTS
    (112, InfoKind::UInt),        // SQL_MAX_BINARY_LITERAL_LEN
    (34, InfoKind::USmallInt),    // SQL_MAX_CATALOG_NAME_LEN
    (108, InfoKind::UInt),        // SQL_MAX_CHAR_LITERAL_LEN
    (97, InfoKind::USmallInt),    // SQL_MAX_COLUMNS_IN_GROUP_BY
    (98, InfoKind::USmallInt),    // SQL_MAX_COLUMNS_IN_INDEX
    (99, InfoKind::USmallInt),    // SQL_MAX_COLUMNS_IN_ORDER_BY
    (100, InfoKind::USmallInt),   // SQL_MAX_COLUMNS_IN_SELECT
    (101, InfoKind::USmallInt),   // SQL_MAX_COLUMNS_IN_TABLE
    (30, InfoKind::USmallInt),    // SQL_MAX_COLUMN_NAME_LEN
    (1, InfoKind::USmallInt),     // SQL_MAX_CONCURRENT_ACTIVITIES
    (31, InfoKind::USmallInt),    // SQL_MAX_CURSOR_NAME_LEN
    (0, InfoKind::USmallInt),     // SQL_MAX_DRIVER_CONNECTIONS
    (10005, InfoKind::USmallInt), // SQL_MAX_IDENTIFIER_LEN
    (102, InfoKind::UInt),        // SQL_MAX_INDEX_SIZE
    (33, InfoKind::USmallInt),    // SQL_MAX_PROCEDURE_NAME_LEN
    (104, InfoKind::UInt),        // SQL_MAX_ROW_SIZE
    (103, InfoKind::YesNo),       // SQL_MAX_ROW_SIZE_INCLUDES_LONG
    (32, InfoKind::USmallInt),    // SQL_MAX_SCHEMA_NAME_LEN
    (105, InfoKind::UInt),        // SQL_MAX_STATEMENT_LEN
    (106, InfoKind::USmallInt),   // SQL_MAX_TABLES_IN_SELECT
    (35, InfoKind::USmallInt),    // SQL_MAX_TABLE_NAME_LEN
    (107, InfoKind::USmallInt),   // SQL_MAX_USER_NAME_LEN
    (37, InfoKind::YesNo),        // SQL_MULTIPLE_ACTIVE_TXN
    (36, InfoKind::YesNo),        // SQL_MULT_RESULT_SETS
    (111, InfoKind::YesNo),       // SQL_NEED_LONG_DATA_LEN
    (75, InfoKind::USmallInt),    // SQL_NON_NULLABLE_COLUMNS
    (85, InfoKind::USmallInt),    // SQL_NULL_COLLATION
    (49, InfoKind::UInt),         // SQL_NUMERIC_FUNCTIONS
    (152, InfoKind::UInt),        // SQL_ODBC_INTERFACE_CONFORMANCE
    (10, InfoKind::Str),          // SQL_ODBC_VER
    (115, InfoKind::UInt),        // SQL_OJ_CAPABILITIES
    (90, InfoKind::YesNo),        // SQL_ORDER_BY_COLUMNS_IN_SELECT
    (153, InfoKind::UInt),        // SQL_PARAM_ARRAY_ROW_COUNTS
    (154, InfoKind::UInt),        // SQL_PARAM_ARRAY_SELECTS
    (21, InfoKind::YesNo),        // SQL_PROCEDURES
    (40, InfoKind::Str),          // SQL_PROCEDURE_TERM
    (93, InfoKind::USmallInt),    // SQL_QUOTED_IDENTIFIER_CASE
    (11, InfoKind::YesNo),        // SQL_ROW_UPDATES
    (39, InfoKind::Str),          // SQL_SCHEMA_TERM
    (91, InfoKind::UInt),         // SQL_SCHEMA_USAGE
    (44, InfoKind::UInt),         // SQL_SCROLL_OPTIONS
    (14, InfoKind::Str),          // SQL_SEARCH_PATTERN_ESCAPE
    (13, InfoKind::Str),          // SQL_SERVER_NAME
    (94, InfoKind::Str),          // SQL_SPECIAL_CHARACTERS
    (155, InfoKind::UInt),        // SQL_SQL92_DATETIME_FUNCTIONS
    (156, InfoKind::UInt),        // SQL_SQL92_FOREIGN_KEY_DELETE_RULE
    (157, InfoKind::UInt),        // SQL_SQL92_FOREIGN_KEY_UPDATE_RULE
    (158, InfoKind::UInt),        // SQL_SQL92_GRANT
    (159, InfoKind::UInt),        // SQL_SQL92_NUMERIC_VALUE_FUNCTIONS
    (160, InfoKind::UInt),        // SQL_SQL92_PREDICATES
    (161, InfoKind::UInt),        // SQL_SQL92_RELATIONAL_JOIN_OPERATORS
    (162, InfoKind::UInt),        // SQL_SQL92_REVOKE
    (163, InfoKind::UInt),        // SQL_SQL92_ROW_VALUE_CONSTRUCTOR
    (164, InfoKind::UInt),        // SQL_SQL92_STRING_FUNCTIONS
    (165, InfoKind::UInt),        // SQL_SQL92_VALUE_EXPRESSIONS
    (118, InfoKind::UInt),        // SQL_SQL_CONFORMANCE
    (166, InfoKind::UInt),        // SQL_STANDARD_CLI_CONFORMANCE
    (167, InfoKind::UInt),        // SQL_STATIC_CURSOR_ATTRIBUTES1
    (168, InfoKind::UInt),        // SQL_STATIC_CURSOR_ATTRIBUTES2
    (50, InfoKind::UInt),         // SQL_STRING_FUNCTIONS
    (95, InfoKind::UInt),         // SQL_SUBQUERIES
    (51, InfoKind::UInt),         // SQL_SYSTEM_FUNCTIONS
    (45, InfoKind::Str),          // SQL_TABLE_TERM
    (109, InfoKind::UInt),        // SQL_TIMEDATE_ADD_INTERVALS
    (110, InfoKind::UInt),        // SQL_TIMEDATE_DIFF_INTERVALS
    (52, InfoKind::UInt),         // SQL_TIMEDATE_FUNCTIONS
    (46, InfoKind::USmallInt),    // SQL_TXN_CAPABLE
    (72, InfoKind::UInt),         // SQL_TXN_ISOLATION_OPTION
    (96, InfoKind::UInt),         // SQL_UNION
    (47, InfoKind::Str),          // SQL_USER_NAME
    (10000, InfoKind::Str),       // SQL_XOPEN_CLI_YEAR
];
